name: Stock Check Automation

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'   # 8:00 AM UTC daily


jobs:
  stock-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t stock-checker .

      - name: Run stock checker
        # Add --shm-size=2g to provide more shared memory
        run: docker run --shm-size=2g -e DISCORD_WEBHOOK_URL=${{ secrets.DISCORD_WEBHOOK_URL }} stock-checker
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
